<?php

/**
 * Laika PHP Micro Framework
 * Author: Showket Ahmed
 * Email: riyadhtayf@gmail.com
 * License: MIT
 * This file is part of the Laika PHP Micro Framework.
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Laika\Core\App;

use Twig\Loader\FilesystemLoader as Engine;
use Laika\Core\Helper\Directory;
use Laika\Core\Http\FormError;
use Laika\Core\Helper\Local;
use Laika\Core\Helper\File;
use Laika\Core\Helper\Url;
use Twig\Environment;
use Twig\TwigFilter;

class Template
{
    /**
     * @var object $twig
     */
    protected object $twig;

    /**
     * @var array $vars
     */
    protected array $vars = [];

    /**
     * @var ?string $templateDirectory Template Directory
     */
    protected ?string $templateDirectory;

    /**
     * @var ?string $cacheDirectory Template Cache Directory
     */
    protected ?string $cacheDirectory;

    /**
     * File Extension
     * @var string
     */
    protected string $extension;

    public function __construct(?string $templateSubDirectory = null, ?string $cacheSubDirectory = null)
    {
        // Ensure Template & Cache Paths
        $this->ensureTemplatePath($templateSubDirectory);
        $this->ensureCachePath($cacheSubDirectory);
        $this->extension = 'twig';

        // Run Template Engine
        $engine = new Engine($this->templateDirectory);
        $this->twig = new Environment($engine, [
            'debug' =>  DEBUG,
            'cache' =>  $this->cacheDirectory
        ]);

        // Assign Template Default Vars
        $this->defaultVars();
        // Assign Template Default Filters
        $this->defaultFilters();

        // Load Template Functions File
        $file = new File("{$this->templateDirectory}/functions.php");
        if (!$file->exists()) {
            $file->touch();
            $file->write("<?php\n// Auto Generated By Framework\n// Start Code From Here...\n\n");
        }

        $file->require(true);
    }

    /**
     * Set File Extension
     * @param string $extension File Extension
     * @return void
     */
    public function extension(string $extension): void
    {
        $this->extension = $extension;
        return;
    }

    /**
     * Render View
     * @param string $name View Name
     * @return string Rendered View
     */
    public function view(string $name): string
    {
        return $this->twig->render("{$name}.{$this->extension}", $this->vars);
    }

    /**
     * Assign Variable
     * @param string|array $key Key Name or Array of Key, Value Pair
     * @param mixed $value Key Name or Array of Key, Value Pair
     */
    public function assign(string|array $key, mixed $value = null): void
    {
        if (is_string($key)) {
            $key = [$key => $value];
        }
        $this->vars = array_merge($this->vars, $key);
    }

    /**
     * @param string $name Filter Name
     * @param string|callable $callable Callable Filter
     * @return void
     */
    public function addFilter(string $name, string|callable $callable): void
    {
        $this->twig->addFilter(new TwigFilter($name, $callable));
    }

    /**
     * Get Assigned Vars
     * @return array
     */
    public function vars(): array
    {
        return $this->vars;
    }

    ##################################################################################
    /*-------------------------------- INTERNAL API --------------------------------*/
    ##################################################################################

    /**
     * Ensure Template Path
     * @param ?string $subdir Sub Directory Path
     * @return void
     */
    protected function ensureTemplatePath(?string $subdir = null): void
    {
        $subdir = $subdir ? trim($subdir, '/') : '';
        $this->templateDirectory = is_dir($subdir) ? $subdir : APP_PATH . "/lf-templates/{$subdir}";
        $this->templateDirectory = rtrim($this->templateDirectory, '/');
        Directory::make($this->templateDirectory);
    }

    /**
     * Ensure Cache Path
     * @param ?string $subdir Sub Directory Path
     * @return void
     */
    protected function ensureCachePath(?string $subdir = null): void
    {
        $subdir = $subdir ? trim($subdir, '/') : '';
        $this->cacheDirectory = is_dir($subdir) ? $subdir : APP_PATH . "/lf-cache/{$subdir}";
        $this->cacheDirectory = rtrim($this->cacheDirectory, '/');
        Directory::make($this->cacheDirectory);
    }

    /**
     * Assign Default Vars
     * @return void
     */
    protected function defaultVars()
    {
        // Assign Local Name. Default is en
        $this->assign('local', Local::get());
        // Assign Form Errors
        $this->assign('errors', FormError::get());
        FormError::clear();
    }

    /**
     * Assign Default Filters
     * @return void
     */
    protected function defaultFilters()
    {
        $url = new Url();
        // Register Hooks
        $this->addFilter('hook', 'do_hook');
        // Register Slugs
        $this->addFilter('slug', function (int $index) use($url) { return $url->segment($index); });
        // Register Queries
        $this->addFilter('query', function (string $key) use($url) { return $url->query($key); });
        // Register Named
        $this->addFilter('named', function(string $name, array $params = []){
            return \named($name, $params, true);
        });
    }
}
